### PR TITLE
Use jupytext.

### PR DESCRIPTION
**Pull request by mkcor**
Hi @ana42742,

PR #1 should be merged before this one.

I realize it's time we use [Jupytext](https://jupytext.readthedocs.io/en/latest/index.html), as @lagru recommended from the beginning! Since our current notebooks contain mostly code, I believe we should use the `py:percent` [format](https://jupytext.readthedocs.io/en/latest/formats-scripts.html#the-percent-format) for now.

Could you please rewrite `embryo/mouse-embryo.ipynb` into the `py:percent` file I started (i.e., `embryo/segment_2D_0.py`)? I named it this way, anticipating that we'll have multiple notebooks for 2D segmentation (and, later, multiple notebooks for 3D segmentation). As you can see, I suggest that we use a `data/` subdirectory (locally) for storing data files.

### CODE REVIEW

**Comment by mkcor** [comment]
@ana42742 as discussed, I've copied your notebook into the .py file -- I've made minor changes (please open it locally with Jupyter to run it and double check).

Local thresholding really shines in this application! :star_struck: 

Great work playing with the offset parameter.

Next step would be to try and detect (label) regions; what do you think?

**Comment by lagru** [comment]
If you want you could also add the following file to pin that [configuration](https://jupytext.readthedocs.io/en/latest/config.html).

```toml
# jupytext.toml
# Pair ipynb notebooks to py:percent text notebooks
formats = "py:percent"
```

Note, with JupyterLab you need to right-click on the .py files and select "Open as notebook". I've also had problems with the jupytext plugin on JupyterLab in the past. In that case using the Jupyter notebook interface has worked.

**Comment by mkcor** [comment]
I've noticed that one of the thresholding techniques doesn't render (between Otsu and Triangle). Would you mind opening an issue for this, @ana42742?

**Comment by mkcor** [comment]
> If you want you could also add the following file to pin that [configuration](https://jupytext.readthedocs.io/en/latest/config.html).
> 
> ```toml
> # jupytext.toml
> # Pair ipynb notebooks to py:percent text notebooks
> formats = "py:percent"
> ```

Thanks. I don't think we want to pin anything for now; that would require cleaning up the repo; I want to keep it a messy sandbox for now, so we don't add any barrier wrt sharing any work in progress...
 
> Note, with JupyterLab you need to right-click on the .py files and select "Open as notebook".

Yes, this is well [documented](https://jupytext.readthedocs.io/en/latest/index.html#installation).

> I've also had problems with the jupytext plugin on JupyterLab in the past. In that case using the Jupyter notebook interface has worked.

So far, I haven't run into any problem -- I've followed the instructions in the above-mentioned (official) docs. I open and edit notebooks in JupyterLab.

**Review by lagru — APPROVED** [review]
Feel welcome to merge. :)

**Comment by mkcor** [comment]
> I've noticed that one of the thresholding techniques doesn't render (between Otsu and Triangle). Would you mind opening an issue for this, @ana42742?

@ana42742 thanks for taking care of this: https://github.com/scikit-image/scikit-image/issues/7084

**Pull request merged**
